import { ShopItem, Achievement, GameMission } from '../types';

export const TRANSLATIONS = {
  pt: {
    title: 'LogicMatch',
    subtitle: 'Logic Master',
    play: 'Jogar',
    back: 'Voltar',
    classic: 'Clássico',
    relax: 'Relaxado',
    timed: 'Cronometrado',
    challenge: 'Escuro',
    survival: 'Sobrevivência',
    frozen: 'Congelado',
    bombs: 'Bombas',
    locks: 'Cadeados',
    multipliers: 'Multiplicadores',
    infinite: 'Modo Infinito',
    easy: 'Fácil',
    medium: 'Médio',
    hard: 'Difícil',
    insane: 'Insano',
    score: 'Pontos',
    highScore: 'Recorde',
    level: 'Nível',
    combo: 'Combo',
    multiplier: 'Mult',
    coins: 'Moedas',
    moves: 'Jogadas',
    time: 'Tempo',
    shop: 'Loja',
    achievements: 'Conquistas',
    missions: 'Missões',
    stats: 'Estatísticas',
    settings: 'Ajustes',
    game_over: 'Fim de Jogo!',
    victory: 'Vitória!',
    board_full: 'Tabuleiro Cheio!',
    try_again: 'Tentar Novamente',
    continue: 'Continuar',
    reset: 'Resetar',
    sound: 'Sons',
    music: 'Música',
    vibration: 'Vibração',
    animations: 'Animações',
    fps: 'Mostrar FPS',
    language: 'Idioma',
    clear_data: 'Limpar Tudo',
    export_data: 'Exportar Progresso',
    import_data: 'Importar Progresso',
    daily_missions: 'Missões Diárias',
    weekly_missions: 'Missões Semanais',
    permanent_missions: 'Desafios Eternos',
    unlocked: 'Desbloqueado!',
    locked_item: 'Bloqueado',
    buy: 'Comprar',
    equip: 'Equipar',
    equipped: 'Equipado',
    not_enough_coins: 'Moedas insuficientes!',
    add_numbers: 'Adicionar Números',
    hint: 'Dica',
    hint_no_moves: 'Não há movimentos disponíveis! Clique em Adicionar.',
    objectives: 'Objetivos',
    clear_target: 'Limpar {n} peças',
    score_target: 'Chegar a {n} pontos',
    target: 'Objetivo',
    special_ice: 'Gelo',
    special_lock: 'Cadeado',
    special_bomb: 'Bomba',
    special_multiplier: 'Multiplicador',
    special_portal: 'Portal',
    profile: 'Perfil',
    confirm_clear: 'Tem certeza que quer apagar TODO seu progresso? Isso não pode ser desfeito.',
    data_imported: 'Dados importados com sucesso!',
    data_invalid: 'Arquivo de backup inválido!',
    time_left: 'Tempo restante',
    sec: 's',
    consecutive_days: 'Dias seguidos',
    total_matches: 'Total de partidas',
    total_clears: 'Peças eliminadas',
    max_combo_reached: 'Maior combo',
    total_time: 'Tempo jogado',
    xp_gained: 'XP ganho',
    coins_gained: 'Moedas ganhas',
    challenge_completed: 'Desafio Concluído!',
    no_more_hints: 'Sem dicas restantes!',
    level_up: 'Subiu de Nível!',
    // Achievements descriptions
    ach_score_1: 'Pioneiro dos Pontos',
    ach_score_1_desc: 'Alcance 1.000 pontos em qualquer partida.',
    ach_score_2: 'Mestre dos Números',
    ach_score_2_desc: 'Alcance 5.000 pontos.',
    ach_score_3: 'Sábio Supremo',
    ach_score_3_desc: 'Alcance 20.000 pontos.',
    ach_clears_1: 'Iniciante do Limbo',
    ach_clears_1_desc: 'Elimine 100 números.',
    ach_clears_2: 'Trator Digital',
    ach_clears_2_desc: 'Elimine 1.000 números.',
    ach_clears_3: 'Destruidor de Infinitos',
    ach_clears_3_desc: 'Elimine 10.000 números.',
    ach_combo_1: 'Dupla Perfeita',
    ach_combo_1_desc: 'Consiga um combo de 5x.',
    ach_combo_2: 'Cascata de Números',
    ach_combo_2_desc: 'Consiga um combo de 12x.',
    ach_combo_3: 'Sincronia Absoluta',
    ach_combo_3_desc: 'Consiga um combo de 25x.',
    ach_games_1: 'Primeiro Passo',
    ach_games_1_desc: 'Jogue sua primeira partida.',
    ach_games_2: 'Fiel Seguidor',
    ach_games_2_desc: 'Complete 50 partidas.',
    ach_games_3: 'Veterano de Guerra',
    ach_games_3_desc: 'Complete 200 partidas.',
    ach_coins_1: 'Bolsos Cheios',
    ach_coins_1_desc: 'Acumule 500 moedas.',
    ach_coins_2: 'Capitalista',
    ach_coins_2_desc: 'Acumule 2.500 moedas.',
    ach_coins_3: 'Magnata da Lógica',
    ach_coins_3_desc: 'Acumule 10.000 moedas.',
    ach_level_1: 'Aprendiz do Fluxo',
    ach_level_1_desc: 'Chegue ao Nível 5.',
    ach_level_2: 'Doutor da Lógica',
    ach_level_2_desc: 'Chegue ao Nível 20.',
    ach_level_3: 'Iluminado',
    ach_level_3_desc: 'Chegue ao Nível 50.',
    ach_special_1: 'Quebra-Gelo',
    ach_special_1_desc: 'Derreta 100 blocos de gelo.',
    ach_special_2: 'Chaveiro',
    ach_special_2_desc: 'Destranque 100 cadeados.',
    ach_special_3: 'Artilheiro',
    ach_special_3_desc: 'Detone 100 bombas.',
    ach_mode_insane: 'Mente Brilhante',
    ach_mode_insane_desc: 'Vença uma partida no modo Insano.'
  },
  en: {
    title: 'LogicMatch',
    subtitle: 'Logic Master',
    play: 'Play',
    back: 'Back',
    classic: 'Classic',
    relax: 'Relax',
    timed: 'Timed',
    challenge: 'Dark Mode',
    survival: 'Survival',
    frozen: 'Frozen',
    bombs: 'Bombs',
    locks: 'Locks',
    multipliers: 'Multipliers',
    infinite: 'Infinite Mode',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    insane: 'Insane',
    score: 'Score',
    highScore: 'High Score',
    level: 'Level',
    combo: 'Combo',
    multiplier: 'Mult',
    coins: 'Coins',
    moves: 'Moves',
    time: 'Time',
    shop: 'Shop',
    achievements: 'Achievements',
    missions: 'Missions',
    stats: 'Stats',
    settings: 'Settings',
    game_over: 'Game Over!',
    victory: 'Victory!',
    board_full: 'Board Full!',
    try_again: 'Try Again',
    continue: 'Continue',
    reset: 'Reset',
    sound: 'Sound',
    music: 'Music',
    vibration: 'Vibration',
    animations: 'Animations',
    fps: 'Show FPS',
    language: 'Language',
    clear_data: 'Clear Progress',
    export_data: 'Export Progress',
    import_data: 'Import Progress',
    daily_missions: 'Daily Missions',
    weekly_missions: 'Weekly Missions',
    permanent_missions: 'Eternal Challenges',
    unlocked: 'Unlocked!',
    locked_item: 'Locked',
    buy: 'Buy',
    equip: 'Equip',
    equipped: 'Equipped',
    not_enough_coins: 'Not enough coins!',
    add_numbers: 'Add Numbers',
    hint: 'Hint',
    hint_no_moves: 'No matches available! Tap Add Numbers.',
    objectives: 'Objectives',
    clear_target: 'Clear {n} pieces',
    score_target: 'Reach {n} score',
    target: 'Goal',
    special_ice: 'Ice',
    special_lock: 'Lock',
    special_bomb: 'Bomb',
    special_multiplier: 'Multiplier',
    special_portal: 'Portal',
    profile: 'Profile',
    confirm_clear: 'Are you sure you want to clear ALL your progress? This cannot be undone.',
    data_imported: 'Progress imported successfully!',
    data_invalid: 'Invalid backup file!',
    time_left: 'Time left',
    sec: 's',
    consecutive_days: 'Daily streak',
    total_matches: 'Total matches',
    total_clears: 'Cleared pieces',
    max_combo_reached: 'Max combo',
    total_time: 'Time played',
    xp_gained: 'XP gained',
    coins_gained: 'Coins earned',
    challenge_completed: 'Challenge Completed!',
    no_more_hints: 'No hints left!',
    level_up: 'Level Up!',
    ach_score_1: 'Points Pioneer',
    ach_score_1_desc: 'Reach 1,000 points in any match.',
    ach_score_2: 'Number Master',
    ach_score_2_desc: 'Reach 5,000 points.',
    ach_score_3: 'Supreme Sage',
    ach_score_3_desc: 'Reach 20,000 points.',
    ach_clears_1: 'Limbo Novice',
    ach_clears_1_desc: 'Clear 100 numbers.',
    ach_clears_2: 'Digital Bulldozer',
    ach_clears_2_desc: 'Clear 1,000 numbers.',
    ach_clears_3: 'Infinity Destroyer',
    ach_clears_3_desc: 'Clear 10,000 numbers.',
    ach_combo_1: 'Perfect Pair',
    ach_combo_1_desc: 'Reach a 5x combo.',
    ach_combo_2: 'Number Cascade',
    ach_combo_2_desc: 'Reach a 12x combo.',
    ach_combo_3: 'Absolute Sync',
    ach_combo_3_desc: 'Reach a 25x combo.',
    ach_games_1: 'First Step',
    ach_games_1_desc: 'Play your first game.',
    ach_games_2: 'Loyal Follower',
    ach_games_2_desc: 'Complete 50 games.',
    ach_games_3: 'War Veteran',
    ach_games_3_desc: 'Complete 200 games.',
    ach_coins_1: 'Lined Pockets',
    ach_coins_1_desc: 'Acumulate 500 coins.',
    ach_coins_2: 'Capitalist',
    ach_coins_2_desc: 'Acumulate 2,500 coins.',
    ach_coins_3: 'Logic Tycoon',
    ach_coins_3_desc: 'Acumulate 10,000 coins.',
    ach_level_1: 'Flow Apprentice',
    ach_level_1_desc: 'Reach Level 5.',
    ach_level_2: 'Logic Doctor',
    ach_level_2_desc: 'Reach Level 20.',
    ach_level_3: 'Enlightened One',
    ach_level_3_desc: 'Reach Level 50.',
    ach_special_1: 'Icebreaker',
    ach_special_1_desc: 'Melt 100 ice blocks.',
    ach_special_2: 'Locksmith',
    ach_special_2_desc: 'Unlock 100 padlocks.',
    ach_special_3: 'Bombardier',
    ach_special_3_desc: 'Detonate 100 bombs.',
    ach_mode_insane: 'Brilliant Mind',
    ach_mode_insane_desc: 'Win a game on Insane difficulty.'
  },
  es: {
    title: 'LogicMatch',
    subtitle: 'Logic Master',
    play: 'Jugar',
    back: 'Volver',
    classic: 'Clásico',
    relax: 'Relax',
    timed: 'Contrarreloj',
    challenge: 'Oscuro',
    survival: 'Supervivencia',
    frozen: 'Congelado',
    bombs: 'Bombas',
    locks: 'Candados',
    multipliers: 'Multiplicadores',
    infinite: 'Modo Infinito',
    easy: 'Fácil',
    medium: 'Medio',
    hard: 'Difícil',
    insane: 'Insano',
    score: 'Puntos',
    highScore: 'Récord',
    level: 'Nivel',
    combo: 'Combo',
    multiplier: 'Mult',
    coins: 'Monedas',
    moves: 'Movimientos',
    time: 'Tiempo',
    shop: 'Tienda',
    achievements: 'Logros',
    missions: 'Misiones',
    stats: 'Estadísticas',
    settings: 'Ajustes',
    game_over: '¡Fin de Juego!',
    victory: '¡Victoria!',
    board_full: '¡Tablero Lleno!',
    try_again: 'Intentar de Nuevo',
    continue: 'Continuar',
    reset: 'Restablecer',
    sound: 'Sonidos',
    music: 'Música',
    vibration: 'Vibración',
    animations: 'Animaciones',
    fps: 'Mostrar FPS',
    language: 'Idioma',
    clear_data: 'Borrar Progreso',
    export_data: 'Exportar Progresso',
    import_data: 'Importar Progresso',
    daily_missions: 'Misiones Diarias',
    weekly_missions: 'Misiones Semanales',
    permanent_missions: 'Desafíos Eternos',
    unlocked: '¡Desbloqueado!',
    locked_item: 'Bloqueado',
    buy: 'Comprar',
    equip: 'Equipar',
    equipped: 'Equipado',
    not_enough_coins: '¡Monedas insuficientes!',
    add_numbers: 'Añadir Números',
    hint: 'Pista',
    hint_no_moves: '¡No hay jugadas disponibles! Haz clic en Añadir.',
    objectives: 'Objetivos',
    clear_target: 'Eliminar {n} fichas',
    score_target: 'Llegar a {n} puntos',
    target: 'Objetivo',
    special_ice: 'Hielo',
    special_lock: 'Candado',
    special_bomb: 'Bomba',
    special_multiplier: 'Multiplicador',
    special_portal: 'Portal',
    profile: 'Perfil',
    confirm_clear: '¿Estás seguro de que deseas borrar TODO tu progreso? No se puede deshacer.',
    data_imported: '¡Progreso importado con éxito!',
    data_invalid: '¡Archivo de respaldo inválido!',
    time_left: 'Tiempo restante',
    sec: 's',
    consecutive_days: 'Racha diaria',
    total_matches: 'Partidas totales',
    total_clears: 'Fichas eliminadas',
    max_combo_reached: 'Mayor combo',
    total_time: 'Tiempo jugado',
    xp_gained: 'XP ganado',
    coins_gained: 'Monedas ganadas',
    challenge_completed: '¡Desafío Completado!',
    no_more_hints: '¡No quedan pistas!',
    level_up: '¡Subiste de Nivel!',
    ach_score_1: 'Pionero de Puntos',
    ach_score_1_desc: 'Alcanza 1.000 puntos en cualquier partida.',
    ach_score_2: 'Maestro de Números',
    ach_score_2_desc: 'Alcanza 5.000 puntos.',
    ach_score_3: 'Sabio Supremo',
    ach_score_3_desc: 'Alcanza 20.000 puntos.',
    ach_clears_1: 'Novato del Limbo',
    ach_clears_1_desc: 'Elimina 100 números.',
    ach_clears_2: 'Excavadora Digital',
    ach_clears_2_desc: 'Elimina 1.000 números.',
    ach_clears_3: 'Destructor del Infinito',
    ach_clears_3_desc: 'Elimina 10.000 números.',
    ach_combo_1: 'Pareja Perfecta',
    ach_combo_1_desc: 'Consigue un combo de 5x.',
    ach_combo_2: 'Cascada de Números',
    ach_combo_2_desc: 'Consigue un combo de 12x.',
    ach_combo_3: 'Sincronía Absoluta',
    ach_combo_3_desc: 'Consigue un combo de 25x.',
    ach_games_1: 'Primer Paso',
    ach_games_1_desc: 'Juega tu primera partida.',
    ach_games_2: 'Seguidor Fiel',
    ach_games_2_desc: 'Completa 50 partidas.',
    ach_games_3: 'Veterano de Guerra',
    ach_games_3_desc: 'Completa 200 partidas.',
    ach_coins_1: 'Bolsillos Llenos',
    ach_coins_1_desc: 'Acumula 500 monedas.',
    ach_coins_2: 'Capitalista',
    ach_coins_2_desc: 'Acumula 2.500 monedas.',
    ach_coins_3: 'Magnate Lógico',
    ach_coins_3_desc: 'Acumule 10.000 monedas.',
    ach_level_1: 'Aprendiz del Flujo',
    ach_level_1_desc: 'Llega al Nivel 5.',
    ach_level_2: 'Doctor de la Lógica',
    ach_level_2_desc: 'Llega al Nivel 20.',
    ach_level_3: 'Iluminado',
    ach_level_3_desc: 'Llega al Nivel 50.',
    ach_special_1: 'Rompehielo',
    ach_special_1_desc: 'Derrite 100 bloques de hielo.',
    ach_special_2: 'Cerrajero',
    ach_special_2_desc: 'Desbloquea 100 candados.',
    ach_special_3: 'Bombardero',
    ach_special_3_desc: 'Detona 100 bombas.',
    ach_mode_insane: 'Mente Brillante',
    ach_mode_insane_desc: 'Gana una partida en dificultad Insano.'
  }
};

export const THEMES = [
  {
    id: 'aurelius',
    name: 'Aurelius Cream',
    bg: 'bg-[#FAF6F0] text-[#3E342A]',
    gridBg: 'bg-[#F0E8DC] border-[#DFD4C4]',
    cellBg: 'bg-white border-[#E6DCCE] text-[#3E342A] hover:border-[#B5945B] hover:shadow-[0_4px_12px_rgba(181,148,91,0.08)] shadow-[0_2px_4px_rgba(62,52,42,0.03)]',
    cellEmpty: 'bg-[#E6DCCE]/25 border-dashed border-[#DFD4C4]',
    cellSelected: 'bg-[#F5EBD7] border-[#B5945B] text-[#87672E] shadow-[0_2px_8px_rgba(181,148,91,0.2)]',
    primaryBtn: 'bg-[#B5945B] text-white hover:bg-[#A38148] active:scale-95 shadow-[0_2px_6px_rgba(181,148,91,0.25)]',
    secondaryBtn: 'border border-[#3E342A]/15 text-[#3E342A] hover:bg-[#3E342A]/5 active:scale-95',
    accentColor: '#B5945B',
    accentText: 'text-[#B5945B]',
    cardBg: 'bg-white border-[#EBDCC9] shadow-[0_10px_30px_rgba(62,52,42,0.08)]',
    itemBg: 'bg-[#FCFAF7] border-[#EBDCC9] hover:border-[#B5945B]',
    itemBgActive: 'bg-[#F5EBD7] border-[#B5945B]',
    textPrimary: 'text-[#3E342A]',
    textSecondary: 'text-[#877869]',
    borderPrimary: 'border-[#EBDCC9]',
    borderSecondary: 'border-[#EBDCC9]/55',
    cardBgHover: 'hover:bg-[#FBF9F6]',
    overlay: 'bg-[#251F1A]/40 backdrop-blur-md'
  },
  {
    id: 'minimalist',
    name: 'Swiss Minimalist',
    bg: 'bg-[#F4F4F5] text-[#18181B]',
    gridBg: 'bg-[#E4E4E7] border-[#D4D4D8]',
    cellBg: 'bg-white border-[#D4D4D8] text-[#18181B] hover:border-[#18181B] hover:shadow-[0_4px_12px_rgba(0,0,0,0.05)] shadow-[0_2px_4px_rgba(0,0,0,0.02)]',
    cellEmpty: 'bg-[#E4E4E7]/30 border-dashed border-[#D4D4D8]',
    cellSelected: 'bg-[#18181B]/5 border-[#18181B] text-[#18181B]',
    primaryBtn: 'bg-[#18181B] text-white hover:bg-[#27272A] active:scale-95 shadow-[0_2px_6px_rgba(24,24,27,0.15)]',
    secondaryBtn: 'border border-[#18181B]/15 text-[#18181B] hover:bg-[#18181B]/5 active:scale-95',
    accentColor: '#18181B',
    accentText: 'text-[#18181B]',
    cardBg: 'bg-white border-[#E4E4E7] shadow-[0_10px_30px_rgba(0,0,0,0.05)]',
    itemBg: 'bg-[#FAFAFA] border-[#E4E4E7] hover:border-[#18181B]',
    itemBgActive: 'bg-[#18181B]/5 border-[#18181B]',
    textPrimary: 'text-[#18181B]',
    textSecondary: 'text-[#71717A]',
    borderPrimary: 'border-[#E4E4E7]',
    borderSecondary: 'border-[#E4E4E7]/60',
    cardBgHover: 'hover:bg-[#FAFAFA]',
    overlay: 'bg-[#18181B]/30 backdrop-blur-md'
  },
  {
    id: 'wood',
    name: 'Carvalho Colonial',
    bg: 'bg-[#F4EBE1] text-[#4A2F1B]',
    gridBg: 'bg-[#DFCEBC] border-[#C8B29B]',
    cellBg: 'bg-[#FAF6F0] border-[#C8B29B] text-[#4A2F1B] hover:border-[#A67C52] hover:shadow-[0_4px_10px_rgba(166,124,82,0.1)] shadow-[0_2px_4px_rgba(0,0,0,0.03)]',
    cellEmpty: 'bg-[#DFCEBC]/30 border-dashed border-[#C8B29B]',
    cellSelected: 'bg-[#F3E5D8] border-[#A67C52] text-[#8C5832] shadow-[0_2px_8px_rgba(166,124,82,0.2)]',
    primaryBtn: 'bg-[#A67C52] text-white hover:bg-[#BC946C] active:scale-95 shadow-[0_2px_6px_rgba(166,124,82,0.2)]',
    secondaryBtn: 'border border-[#4A2F1B]/15 text-[#4A2F1B] hover:bg-[#4A2F1B]/5 active:scale-95',
    accentColor: '#A67C52',
    accentText: 'text-[#A67C52]',
    cardBg: 'bg-[#FAF6F0] border-[#E5D7C6] shadow-[0_10px_30px_rgba(74,47,27,0.06)]',
    itemBg: 'bg-[#FCFAF7] border-[#E5D7C6] hover:border-[#A67C52]',
    itemBgActive: 'bg-[#F3E5D8] border-[#A67C52]',
    textPrimary: 'text-[#4A2F1B]',
    textSecondary: 'text-[#8C715C]',
    borderPrimary: 'border-[#E5D7C6]',
    borderSecondary: 'border-[#E5D7C6]/60',
    cardBgHover: 'hover:bg-[#F9F4EE]',
    overlay: 'bg-[#2D1B10]/40 backdrop-blur-md'
  },
  {
    id: 'space',
    name: 'Nebula Space',
    bg: 'bg-[#08081A] text-[#E0E7FF]',
    gridBg: 'bg-[#0E0E2E] border-[#312E81]',
    cellBg: 'bg-[#14143D] border-[#1E1B4B] text-[#FFFFFF] hover:border-[#818CF8] hover:shadow-[0_0_12px_rgba(129,140,248,0.3)]',
    cellEmpty: 'bg-[#08081A]/80 border-dashed border-[#1E1B4B]',
    cellSelected: 'bg-[#818CF8]/20 border-[#818CF8] text-[#C7D2FE] shadow-[0_0_15px_rgba(129,140,248,0.4)]',
    primaryBtn: 'bg-gradient-to-r from-[#6366F1] to-[#A855F7] text-white hover:opacity-90 active:scale-95 shadow-[0_4px_12px_rgba(99,102,241,0.3)]',
    secondaryBtn: 'border border-[#6366F1]/30 text-[#A5B4FC] hover:bg-[#6366F1]/10 active:scale-95',
    accentColor: '#818CF8',
    accentText: 'text-[#818CF8]',
    cardBg: 'bg-[#0E0E2E] border-[#1E1B4B] shadow-[0_10px_35px_rgba(0,0,0,0.5)]',
    itemBg: 'bg-[#14143D]/50 border-[#1E1B4B] hover:border-[#6366F1]',
    itemBgActive: 'bg-[#6366F1]/15 border-[#6366F1]',
    textPrimary: 'text-[#FFFFFF]',
    textSecondary: 'text-[#94A3B8]',
    borderPrimary: 'border-[#1E1B4B]',
    borderSecondary: 'border-[#1E1B4B]/50',
    cardBgHover: 'hover:bg-[#14143D]/30',
    overlay: 'bg-black/85 backdrop-blur-md'
  },
  {
    id: 'neon',
    name: 'Neon Grid',
    bg: 'bg-[#000000] text-[#00FFCC]',
    gridBg: 'bg-[#06060A] border-[#00FFCC]/40',
    cellBg: 'bg-[#0F0F15] border-[#FF007F]/30 text-[#FFFFFF] hover:border-[#00FFCC] hover:shadow-[0_0_10px_rgba(0,255,204,0.3)]',
    cellEmpty: 'bg-black border-dotted border-[#FF007F]/20',
    cellSelected: 'bg-[#00FFCC]/15 border-[#00FFCC] text-[#00FFCC] shadow-[0_0_15px_rgba(0,255,204,0.5)]',
    primaryBtn: 'bg-[#00FFCC] text-[#000000] font-black hover:bg-[#33FFDD] active:scale-95 shadow-[0_0_15px_rgba(0,255,204,0.4)]',
    secondaryBtn: 'border border-[#FF007F] text-[#FF007F] hover:bg-[#FF007F]/10 active:scale-95 shadow-[0_0_10px_rgba(255,0,127,0.2)]',
    accentColor: '#00FFCC',
    accentText: 'text-[#00FFCC]',
    cardBg: 'bg-[#06060A] border-[#00FFCC]/20 shadow-[0_0_30px_rgba(0,255,204,0.1)]',
    itemBg: 'bg-[#0F0F15] border-[#FF007F]/20 hover:border-[#00FFCC]',
    itemBgActive: 'bg-[#00FFCC]/10 border-[#00FFCC]',
    textPrimary: 'text-[#FFFFFF]',
    textSecondary: 'text-[#8E8EA0]',
    borderPrimary: 'border-[#FF007F]/20',
    borderSecondary: 'border-[#FF007F]/10',
    cardBgHover: 'hover:bg-[#0F0F15]/50',
    overlay: 'bg-black/90 backdrop-blur-md'
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    bg: 'bg-[#0C0513] text-[#FCEE0A]',
    gridBg: 'bg-[#140B24] border-[#00F0FF]/40',
    cellBg: 'bg-[#1B0D31] border-[#FCEE0A]/30 text-[#FFFFFF] hover:border-[#00F0FF] hover:shadow-[0_0_8px_rgba(0,240,255,0.3)]',
    cellEmpty: 'bg-[#0C0513] border-[#301C4E]',
    cellSelected: 'bg-[#00F0FF]/15 border-[#00F0FF] text-[#00F0FF] shadow-[0_0_12px_rgba(0,240,255,0.4)]',
    primaryBtn: 'bg-[#FCEE0A] text-[#000000] font-bold hover:bg-[#FFFF55] active:scale-95 shadow-[0_4px_10px_rgba(252,238,10,0.2)]',
    secondaryBtn: 'border border-[#00F0FF] text-[#00F0FF] hover:bg-[#00F0FF]/10 active:scale-95',
    accentColor: '#FCEE0A',
    accentText: 'text-[#FCEE0A]',
    cardBg: 'bg-[#140B24] border-[#00F0FF]/20 shadow-2xl',
    itemBg: 'bg-[#1B0D31] border-[#301C4E] hover:border-[#00F0FF]',
    itemBgActive: 'bg-[#00F0FF]/10 border-[#00F0FF]',
    textPrimary: 'text-white',
    textSecondary: 'text-gray-400',
    borderPrimary: 'border-[#00F0FF]/20',
    borderSecondary: 'border-[#301C4E]',
    cardBgHover: 'hover:bg-[#1B0D31]/50',
    overlay: 'bg-black/85 backdrop-blur-md'
  }
];

export const SHOP_ITEMS: ShopItem[] = [
  // Themes
  { id: 'neon', category: 'theme', nameKey: 'Neon Grid', cost: 150, previewColor: '#00ffcc' },
  { id: 'wood', category: 'theme', nameKey: 'Estilo Madeira', cost: 250, previewColor: '#d4a373' },
  { id: 'space', category: 'theme', nameKey: 'Nebula Space', cost: 400, previewColor: '#818cf8' },
  { id: 'cyberpunk', category: 'theme', nameKey: 'Cyberpunk 2077', cost: 600, previewColor: '#fcee0a' },
  { id: 'minimalist', category: 'theme', nameKey: 'Charcoal Minimalist', cost: 800, previewColor: '#ffffff' },

  // Avatars with passive perks!
  { 
    id: 'av_1', 
    category: 'avatar', 
    nameKey: 'Iniciante', 
    cost: 0, 
    previewImage: '🧘',
    perkPT: 'Sem bônus passivo.',
    perkEN: 'No passive perk.',
    perkES: 'Sin bono pasivo.'
  },
  { 
    id: 'av_2', 
    category: 'avatar', 
    nameKey: 'Matemático', 
    cost: 50, 
    previewImage: '🧮',
    perkPT: 'Mente Calculadora: +2 Jogadas extras em fases com limites de jogada.',
    perkEN: 'Calculator Mind: +2 Extra Moves in stage-limited modes.',
    perkES: 'Mente Calculadora: +2 Movimientos extras en niveles limitados.'
  },
  { 
    id: 'av_3', 
    category: 'avatar', 
    nameKey: 'Luminoso', 
    cost: 100, 
    previewImage: '💡',
    perkPT: 'Idéia Brilhante: Inicia com +1 dica grátis em todas as fases.',
    perkEN: 'Bright Idea: Start with +1 free hint in all matches.',
    perkES: 'Idea Brillante: Comienza con +1 pista gratis en todas las partidas.'
  },
  { 
    id: 'av_4', 
    category: 'avatar', 
    nameKey: 'Samurai', 
    cost: 200, 
    previewImage: '⚔️',
    perkPT: 'Foco de Aço: Combo dura +2.0s a mais antes de resetar.',
    perkEN: 'Steel Focus: Combo hold duration is increased by +2.0s.',
    perkES: 'Enfoque de Acero: El combo dura +2.0s más antes de reiniciarse.'
  },
  { 
    id: 'av_5', 
    category: 'avatar', 
    nameKey: 'Foguete', 
    cost: 300, 
    previewImage: '🚀',
    perkPT: 'Propulsão Vital: Inicia com +1 vida extra (erros permitidos) e +1 embaralhar.',
    perkEN: 'Vital Thruster: Start with +1 extra life and +1 extra shuffle.',
    perkES: 'Propulsión Vital: Comienza con +1 vida extra y +1 embarajar adicional.'
  },
  { 
    id: 'av_6', 
    category: 'avatar', 
    nameKey: 'Dragão', 
    cost: 500, 
    previewImage: '🐲',
    perkPT: 'Fogo Destruidor: Detonações dão o dobro de pontos de bônus e o dobro de moedas.',
    perkEN: 'Destructive Fire: Bomb explosions grant double score and double safe coins.',
    perkES: 'Fuego Destructor: Detonaciones dan el doble de puntos y el doble de monedas.'
  },
  { 
    id: 'av_7', 
    category: 'avatar', 
    nameKey: 'Coringa', 
    cost: 800, 
    previewImage: '🃏',
    perkPT: 'Sorte do Palhaço: 10% de chance de ganhar +10 moedas bônus ao fazer qualquer par.',
    perkEN: 'Lucky Match: 10% chance to earn +10 bonus coins on any matched pair.',
    perkES: 'Suerte del bufón: 10% de probabilidad de ganar +10 monedas por pareja.'
  },
  { 
    id: 'av_8', 
    category: 'avatar', 
    nameKey: 'Mago dos Números', 
    cost: 1200, 
    previewImage: '🧙‍♂️',
    perkPT: 'Alquimia Dourada: +25% de moedas ganhas no fim de todas as fases.',
    perkEN: 'Gold Alchemy: +25% bonus coins earned at the end of all matches.',
    perkES: 'Alquimia Dorada: +25% de monedas de bonificación al final de las partidas.'
  },

  // Frames with style descriptions!
  { 
    id: 'fr_1', 
    category: 'frame', 
    nameKey: 'Sem Moldura', 
    cost: 0, 
    previewImage: 'border-transparent',
    perkPT: 'Visual padrão simples e minimalista.',
    perkEN: 'Simple and minimalistic default look.',
    perkES: 'Aspecto simple y minimalista predeterminado.'
  },
  { 
    id: 'fr_2', 
    category: 'frame', 
    nameKey: 'Bronze Fino', 
    cost: 100, 
    previewImage: 'border border-amber-600 shadow-md',
    perkPT: 'Uma moldura estilosa esculpida em bronze polido.',
    perkEN: 'A stylish border sculpted in polished bronze.',
    perkES: 'Un marco elegante esculpido en bronce pulido.'
  },
  { 
    id: 'fr_3', 
    category: 'frame', 
    nameKey: 'Prata Polida', 
    cost: 200, 
    previewImage: 'border-2 border-slate-400 shadow-lg',
    perkPT: 'Moldura brilhante feita de prata maciça e lustrada.',
    perkEN: 'Shining border made of solid, burnished silver.',
    perkES: 'Marco brillante hecho de plata maciza y pulida.'
  },
  { 
    id: 'fr_4', 
    category: 'frame', 
    nameKey: 'Ouro Imperial', 
    cost: 400, 
    previewImage: 'border-2 border-yellow-500 shadow-[0_0_10px_rgba(234,179,8,0.5)]',
    perkPT: 'Moldura real em ouro puro com uma fina aura divina.',
    perkEN: 'Royal pure gold border radiating a subtle divine aura.',
    perkES: 'Marco real de oro puro que irradia una sutil aura divina.'
  },
  { 
    id: 'fr_5', 
    category: 'frame', 
    nameKey: 'Plasma Cyber', 
    cost: 600, 
    previewImage: 'border-2 border-cyan-400 animate-pulse shadow-[0_0_12px_rgba(34,211,238,0.6)]',
    perkPT: 'Moldura de plasma tecnológico neon ciano vibrante.',
    perkEN: 'High-tech neon cyan plasma glowing frame.',
    perkES: 'Marco brillante de plasma de neón cian tecnológico.'
  },
  { 
    id: 'fr_6', 
    category: 'frame', 
    nameKey: 'Fogo Escuro', 
    cost: 1000, 
    previewImage: 'border-2 border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.8)]',
    perkPT: 'Moldura infernal envolta em chamas negras e brasas vermelhas.',
    perkEN: 'Infernal frame engulfed in dark flames and glowing embers.',
    perkES: 'Marco infernal envuelto en llamas oscuras y brasas rojas.'
  }
];

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  // Score Category
  { id: 'score_1000', titleKey: 'ach_score_1', descriptionKey: 'ach_score_1_desc', category: 'score', targetValue: 1000, currentValue: 0, completed: false, rewardCoins: 50 },
  { id: 'score_5000', titleKey: 'ach_score_2', descriptionKey: 'ach_score_2_desc', category: 'score', targetValue: 5000, currentValue: 0, completed: false, rewardCoins: 150 },
  { id: 'score_20000', titleKey: 'ach_score_3', descriptionKey: 'ach_score_3_desc', category: 'score', targetValue: 20000, currentValue: 0, completed: false, rewardCoins: 500 },

  // Clears Category
  { id: 'clears_100', titleKey: 'ach_clears_1', descriptionKey: 'ach_clears_1_desc', category: 'clears', targetValue: 100, currentValue: 0, completed: false, rewardCoins: 30 },
  { id: 'clears_1000', titleKey: 'ach_clears_2', descriptionKey: 'ach_clears_2_desc', category: 'clears', targetValue: 1000, currentValue: 0, completed: false, rewardCoins: 150 },
  { id: 'clears_10000', titleKey: 'ach_clears_3', descriptionKey: 'ach_clears_3_desc', category: 'clears', targetValue: 10000, currentValue: 0, completed: false, rewardCoins: 600 },

  // Combo Category
  { id: 'combo_5', titleKey: 'ach_combo_1', descriptionKey: 'ach_combo_1_desc', category: 'combo', targetValue: 5, currentValue: 0, completed: false, rewardCoins: 40 },
  { id: 'combo_12', titleKey: 'ach_combo_2', descriptionKey: 'ach_combo_2_desc', category: 'combo', targetValue: 12, currentValue: 0, completed: false, rewardCoins: 120 },
  { id: 'combo_25', titleKey: 'ach_combo_3', descriptionKey: 'ach_combo_3_desc', category: 'combo', targetValue: 25, currentValue: 0, completed: false, rewardCoins: 400 },

  // Games Category
  { id: 'games_1', titleKey: 'ach_games_1', descriptionKey: 'ach_games_1_desc', category: 'games', targetValue: 1, currentValue: 0, completed: false, rewardCoins: 20 },
  { id: 'games_50', titleKey: 'ach_games_2', descriptionKey: 'ach_games_2_desc', category: 'games', targetValue: 50, currentValue: 0, completed: false, rewardCoins: 150 },
  { id: 'games_200', titleKey: 'ach_games_3', descriptionKey: 'ach_games_3_desc', category: 'games', targetValue: 200, currentValue: 0, completed: false, rewardCoins: 500 },

  // Coins Category
  { id: 'coins_500', titleKey: 'ach_coins_1', descriptionKey: 'ach_coins_1_desc', category: 'coins', targetValue: 500, currentValue: 0, completed: false, rewardCoins: 50 },
  { id: 'coins_2500', titleKey: 'ach_coins_2', descriptionKey: 'ach_coins_2_desc', category: 'coins', targetValue: 2500, currentValue: 0, completed: false, rewardCoins: 200 },
  { id: 'coins_10000', titleKey: 'ach_coins_3', descriptionKey: 'ach_coins_3_desc', category: 'coins', targetValue: 10000, currentValue: 0, completed: false, rewardCoins: 600 },

  // Level Category
  { id: 'level_5', titleKey: 'ach_level_1', descriptionKey: 'ach_level_1_desc', category: 'special', targetValue: 5, currentValue: 0, completed: false, rewardCoins: 50 },
  { id: 'level_20', titleKey: 'ach_level_2', descriptionKey: 'ach_level_2_desc', category: 'special', targetValue: 20, currentValue: 0, completed: false, rewardCoins: 250 },
  { id: 'level_50', titleKey: 'ach_level_3', descriptionKey: 'ach_level_3_desc', category: 'special', targetValue: 50, currentValue: 0, completed: false, rewardCoins: 800 },

  // Special clears Category
  { id: 'spec_ice_100', titleKey: 'ach_special_1', descriptionKey: 'ach_special_1_desc', category: 'special', targetValue: 100, currentValue: 0, completed: false, rewardCoins: 100 },
  { id: 'spec_lock_100', titleKey: 'ach_special_2', descriptionKey: 'ach_special_2_desc', category: 'special', targetValue: 100, currentValue: 0, completed: false, rewardCoins: 100 },
  { id: 'spec_bomb_100', titleKey: 'ach_special_3', descriptionKey: 'ach_special_3_desc', category: 'special', targetValue: 100, currentValue: 0, completed: false, rewardCoins: 100 },
  
  // Insane difficulty
  { id: 'win_insane', titleKey: 'ach_mode_insane', descriptionKey: 'ach_mode_insane_desc', category: 'special', targetValue: 1, currentValue: 0, completed: false, rewardCoins: 300 }
];

export function getMissions(dateStr: string): GameMission[] {
  // Use date string to seed values so it changes daily/weekly automatically
  let seed = dateStr.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);

  const lcg = () => {
    // Standard LCG parameters
    seed = (seed * 1664525 + 1013904223) % 4294967296;
    return seed / 4294967296;
  };

  const dailyTemplates = [
    {
      id: 'daily_score',
      descriptionKey: 'Reach {n} score in any game',
      targetValue: 1000 + Math.floor(lcg() * 10) * 200, // 1000 to 2800
      rewardCoins: 40,
      rewardXP: 100
    },
    {
      id: 'daily_clears',
      descriptionKey: 'Clear {n} pieces',
      targetValue: 40 + Math.floor(lcg() * 8) * 10, // 40 to 110
      rewardCoins: 50,
      rewardXP: 120
    },
    {
      id: 'daily_games',
      descriptionKey: 'Complete {n} matches',
      targetValue: 2 + Math.floor(lcg() * 3), // 2 to 4
      rewardCoins: 30,
      rewardXP: 80
    },
    {
      id: 'daily_win_classic',
      descriptionKey: 'Win {n} classic games',
      targetValue: 1 + Math.floor(lcg() * 2), // 1 to 2
      rewardCoins: 45,
      rewardXP: 110
    },
    {
      id: 'daily_win_relax',
      descriptionKey: 'Win {n} relax games',
      targetValue: 1 + Math.floor(lcg() * 2), // 1 to 2
      rewardCoins: 35,
      rewardXP: 90
    },
    {
      id: 'daily_trigger_bombs',
      descriptionKey: 'Trigger {n} bombs',
      targetValue: 1 + Math.floor(lcg() * 3), // 1 to 3
      rewardCoins: 40,
      rewardXP: 100
    },
    {
      id: 'daily_combo_streak',
      descriptionKey: 'Achieve a combo of {n}x',
      targetValue: 4 + Math.floor(lcg() * 4), // 4 to 7
      rewardCoins: 50,
      rewardXP: 125
    },
    {
      id: 'daily_melt_ice',
      descriptionKey: 'Melt {n} ice blocks',
      targetValue: 4 + Math.floor(lcg() * 5) * 2, // 4 to 12
      rewardCoins: 45,
      rewardXP: 110
    },
    {
      id: 'daily_unlock_locks',
      descriptionKey: 'Unlock {n} locks',
      targetValue: 4 + Math.floor(lcg() * 5) * 2, // 4 to 12
      rewardCoins: 45,
      rewardXP: 110
    },
    {
      id: 'daily_earn_coins',
      descriptionKey: 'Earn {n} coins from playing',
      targetValue: 50 + Math.floor(lcg() * 10) * 10, // 50 to 140
      rewardCoins: 40,
      rewardXP: 100
    }
  ];

  // Select 3 random unique daily templates using the LCG
  const selectedDailies: GameMission[] = [];
  const templatesCopy = [...dailyTemplates];
  while (selectedDailies.length < 3 && templatesCopy.length > 0) {
    const idx = Math.floor(lcg() * templatesCopy.length);
    const selected = templatesCopy.splice(idx, 1)[0];
    selectedDailies.push({
      id: selected.id,
      type: 'daily',
      descriptionKey: selected.descriptionKey,
      targetValue: selected.targetValue,
      currentValue: 0,
      completed: false,
      rewardCoins: selected.rewardCoins,
      rewardXP: selected.rewardXP
    });
  }

  // Also include the weekly ones so there's always weekly challenges
  const weeklyTemplates: GameMission[] = [
    {
      id: 'weekly_combos',
      type: 'weekly',
      descriptionKey: 'Achieve a combo of {n}x',
      targetValue: 10 + Math.floor(lcg() * 6),
      currentValue: 0,
      completed: false,
      rewardCoins: 150,
      rewardXP: 400
    },
    {
      id: 'weekly_bombs',
      type: 'weekly',
      descriptionKey: 'Trigger {n} bombs',
      targetValue: 15 + Math.floor(lcg() * 10),
      currentValue: 0,
      completed: false,
      rewardCoins: 180,
      rewardXP: 450
    },
    {
      id: 'weekly_coins',
      type: 'weekly',
      descriptionKey: 'Earn {n} coins from playing',
      targetValue: 400 + Math.floor(lcg() * 5) * 100,
      currentValue: 0,
      completed: false,
      rewardCoins: 200,
      rewardXP: 500
    }
  ];

  return [...selectedDailies, ...weeklyTemplates];
}
